# NUMPY 
NumPy, one of the packages that you just can’t miss when you’re learning data science, mainly because this library provides you with an array data structure that holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient. NumPy is a Python library that is the core library for scientific computing in Python. 


In [18]:
import numpy as np


## array
https://numpy.org/doc/1.18/reference/generated/numpy.array.html

In [25]:
a=np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [26]:
a.shape # To check the shape of the array

(2, 2)

In [24]:
a=a.reshape(4,1) #Reshaping
a

array([[1],
       [2],
       [3],
       [4]])

In [28]:
b=np.array([1,23,5])
b.shape

(3,)

In [31]:
b=b.reshape(3,1,1)
b.shape

(3, 1, 1)

## dot

This function returns the dot product of two arrays. For 2-D vectors, it is the equivalent to matrix multiplication. For 1-D arrays, it is the inner product of the vectors. For N-dimensional arrays, it is a sum product over the last axis of a and the second-last axis of b.

https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [7]:
import numpy as np 

a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 

print ("a:",a)
print()
print("b:", b)
np.dot(a,b)
#[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

a: [[1 2]
 [3 4]]

b: [[11 12]
 [13 14]]


array([[37, 40],
       [85, 92]])

https://gfycat.com/ajarselfassuredgoldfish-matrix-multiplication-literature-subject

https://gfycat.com/positiveexhaustedamericangoldfinch



##	Random()function:
Syntax : numpy.random.random(size=None)

Parameters :

size : [int or tuple of ints, optional] 

Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn.

https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randn.html


In [32]:
# output array 
out_arr = np.random.random(size = 3) 
print ("Output 1D Array filled with random floats : ", out_arr)  


Output 1D Array filled with random floats :  [0.14778484 0.966281   0.23410824]


In [34]:
np.random.random((2,3)) 

array([[0.7601183 , 0.63135623, 0.93305606],
       [0.17941127, 0.0872189 , 0.59430067]])

## Slicing

In [38]:
a=np.random.random((5,3)) 
a

array([[0.19206362, 0.1388488 , 0.98478899],
       [0.17432772, 0.80942787, 0.58257633],
       [0.57749172, 0.0954947 , 0.61980562],
       [0.57443566, 0.94398197, 0.75063414],
       [0.138224  , 0.2416645 , 0.99889499]])

In [39]:
a.shape

(5, 3)

In [40]:
a[1:3,1:3]

array([[0.80942787, 0.58257633],
       [0.0954947 , 0.61980562]])

In [41]:
a[:,:2]

array([[0.19206362, 0.1388488 ],
       [0.17432772, 0.80942787],
       [0.57749172, 0.0954947 ],
       [0.57443566, 0.94398197],
       [0.138224  , 0.2416645 ]])

## Sum()function:
numpy.sum(arr, axis, dtype, out) : 

This function returns the sum of array elements over the specified axis.

https://numpy.org/doc/1.18/reference/generated/numpy.sum.html

In [42]:
# 1D array  
arr = [20, 2, .2, 10, 4]   
   
print("Sum of arr : ", np.sum(arr))  


Sum of arr :  36.2


In [46]:
arr=np.array([[0, 1], [0, 5],[2,8]])
print(arr)
np.sum(arr, axis=1)


[[0 1]
 [0 5]
 [2 8]]


array([ 1,  5, 10])

In [47]:
np.sum(arr)

16

## Square()function:
This mathematical function helps user to calculate square value of each element in the array.

https://numpy.org/doc/stable/reference/generated/numpy.square.html

In [17]:
arr1 = [1, -3, 15, -466] 
print ("Square Value of arr1 : \n", np.square(arr1)) 


Square Value of arr1 : 
 [     1      9    225 217156]
